export const DONORS = [
  {
    id: 0,
    firstname: "Aisha",
    lastname: "Khan",
    email: "aisha@khan.com",
    telnum: 123456789,
    age: 17,
    city: "Karachi",
    country: "Pakistan",
    bloodGroup: "A+",
  },
  {
    id: 1,
    firstname: "Nadia",
    lastname: "Shoukat",
    email: "nadia@shoukat.com",
    telnum: 123456789,
    age: 24,
    city: "Karachi",
    country: "Pakistan",
    bloodGroup: "O+",
  },
  {
    id: 2,
    firstname: "Alina",
    lastname: "Azam",
    email: "alina@azam.com",
    telnum: 123456789,
    age: 22,
    city: "Karachi",
    country: "Pakistan",
    bloodGroup: "AB-",
  },
  {
    id: 3,
    firstname: "Alina",
    lastname: "Azam",
    email: "alina@azam.com",
    telnum: 123456789,
    age: 22,
    city: "Karachi",
    country: "Pakistan",
    bloodGroup: "AB-",
  },
  {
    id: 4,
    firstname: "Alina",
    lastname: "Azam",
    email: "alina@azam.com",
    telnum: 123456789,
    age: 22,
    city: "Karachi",
    country: "Pakistan",
    bloodGroup: "AB-",
  },
];
